<a href="https://colab.research.google.com/github/CeeCeeOkeke/PortfolioProject/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


List Vs Numpy - Time Taken


In [6]:
python_list = [i for i in range (10000)]

start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(end_time - start_time)

NameError: ignored

Numpy Arrays


In [8]:
list1 = [1,2,3,4,5,6,7]
print(list1)
type(list1)

[1, 2, 3, 4, 5, 6, 7]


list

In [9]:
np_array = np.array([1,2,3,4,5,6])
print(np_array)
type(np_array)

[1 2 3 4 5 6]


numpy.ndarray

craeting non dimensional array

In [11]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [13]:
b = np.array([(1,2,3,4), (5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
b.shape

(2, 4)

In [18]:
c = np.array([(1,2,3,4), (5,6,7,8)],dtype= float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in Numpy Arrays

In [21]:
# create a numpy arrays of zeros
x = np.zeros((4,5))
print(x)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [23]:
#Create numpy arrays of ones
y = np.ones((3,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [30]:
#create an array of a particular value
z = np.full((5,4), 5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [33]:
#crating an identity Matrix
a = np.eye((4),dtype = float)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [45]:
#create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.90119287 0.64506894 0.31097825 0.35706794]
 [0.15631909 0.66552277 0.08533087 0.57410886]
 [0.46101104 0.21717728 0.29438176 0.49841188]]


In [49]:
#create a numpy array with random integer values
z = np.random.randint(13, 100,(4,6))
print(z)

[[25 77 47 41 81 52]
 [44 18 24 46 42 51]
 [16 40 38 27 78 98]
 [14 56 41 44 37 17]]


In [53]:
# array of evenly spaced values specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [58]:
#array of evenly spaced values ----> specifying the stop
e = np.arange(10, 50, 5)
print(e)

[10 15 20 25 30 35 40 45]


In [60]:
# Convert a list to a numpy array
list2 = [10, 20, 30, 40, 50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

Analyzing a numpy array

In [63]:
c = np.random.randint(10, 50, (5,5))
print(c)

[[13 28 14 38 15]
 [25 24 44 18 14]
 [11 33 27 42 34]
 [19 42 28 29 26]
 [48 41 22 24 31]]


In [64]:
# array dimension
print(c.shape)

(5, 5)


In [65]:
# Number of dimensions
print(c.ndim)

2


In [66]:
#  Checking the number of elemrnts in an array
print(c.size)

25


Mathermatical operations on a np array


In [68]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2) # concantenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [74]:
a = np.random.randint(0,10,(3,3))
b = np. random.randint(10, 20,(3,3))
print(a)
print(b)

[[8 5 1]
 [9 7 1]
 [1 2 4]]
[[16 15 17]
 [18 17 17]
 [15 17 10]]


In [72]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[18 25 24]
 [17 21 13]
 [20 16 22]]
[[ -4  -9 -12]
 [-17 -13  -9]
 [ -8  -6  -4]]
[[ 77 136 108]
 [  0  68  22]
 [ 84  55 117]]
[[0.63636364 0.47058824 0.33333333]
 [0.         0.23529412 0.18181818]
 [0.42857143 0.45454545 0.69230769]]


Array Manipulation

In [76]:
array = np.random.randint(0, 10, (2,3))
print(array)
print(array.shape)

[[1 6 3]
 [3 5 8]]
(2, 3)


In [78]:
#transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)


[[1 3]
 [6 5]
 [3 8]]
(3, 2)


In [80]:
#Reshaping an array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[0 8 4]
 [3 7 1]]
(2, 3)


In [81]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[0 8]
 [4 3]
 [7 1]]
(3, 2)
